name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Tests with Code Coverage
      run: 
        npm install
        npm test
        npx c8 mocha my-test.js --reporter mochawesome
    
