name: Test workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests with code coverage
      run: npx c8 mocha my-test.js --reporter mocha-lcov-reporter
      continue-on-error: true

    - name: Send code coverage to coveralls
      run: npx coveralls < coverage/lcov.info
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Generate Mochawesome report
      run: npx mocha my-test.js --reporter mochawesome
      continue-on-error: true
    
