name: Test workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests with code coverage
      run: npx c8 mocha my-test.js --reporter mochawesome
      #run: npx nyc --reporter lcov --report-dir coverage npx mocha my-test.js
      continue-on-error: true

    - name: Send code coverage to coveralls
      #run: npx coveralls --report coverage/**/*.lcov
      #run: npx nyc report --reporter=lcov > coverage/lcov.info && npx coveralls
      run: |
        if [ -d "coverage" ] && [ -f "coverage/lcov.info" ]; then
          npx coveralls
        else
          echo "Code coverage data not found in the 'coverage' directory."
        fi
      
     # run: |
     #   if [ -d "coverage" ] && [ -f "coverage/lcov.info" ]; then
     #     npx mocha-lcov-reporter --output=coverage/lcov-report.info coverage/lcov.info
     #     npx coveralls < coverage/lcov-report.info
     #   else
     #     echo "Code coverage data not found in the 'coverage' directory."
     #   fi
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    #- name: Generate Mochawesome report
    #  run: npx mocha my-test.js --reporter mochawesome
    
