name: Test workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests with code coverage
      run: npx c8 mocha test/**/*.test.js --reporter mochawesome --bail=false
      continue-on-error: true

    - name: Archive Mochawesome report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: mochawesome-report
        path: mochawesome-report

    - name: Send code coverage to coveralls
      run: npx coveralls < coverage/lcov.info
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    
